### PR TITLE
sAdding Serialconsole correction module

### PR DESCRIPTION
**Pull request by malachma**
This is a new module for ALAR2 to fix an incorrect serialconsole setup for Ubuntu, RedHat and Suse.
The module can be used to get a working serialconsole , which can avoid that a recovery VM has to be created even for a simple step like changing the password only.

### CODE REVIEW

**Comment by malachma** [comment]
Hello @haagha could you please review this pull request.

Thanks
Marcus

**Review by haagha — APPROVED** [review]
LGTM!

**Comment by haagha** [comment]
Can you please improve the README.md?

**Comment by malachma** [comment]
@haagha  The new version of the README is available in this PR now. Sorry for the delay.

**Comment by malachma** [comment]
@haagha let me know whether anything else is missing to to a proper commit. 
Thanks Marcus.

**Pull request merged**
