### PR TITLE
Win safe mode script

### PR DESCRIPTION
**Pull request by rjmccallumbigl**
I updated the repair script to be compatible with Domain Controllers by putting them in DSRM (Directory Services Recovery Mode).

### CODE REVIEW

**Comment by rjmccallumbigl** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by haagha** [comment]
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```

@microsoft-github-policy-service agree company="Microsoft"

**Review by haagha — COMMENTED** [review]
Hi Ryan, No comments but I'm curious if we need to output the logs into a file? 

something like this : $logFile = "$env:PUBLIC\Desktop\$($scriptName).log"

**Review by haagha — APPROVED** [review]

**Comment by rjmccallumbigl** [comment]
Sure thing! Will add 👍🏿

**Comment by rjmccallumbigl** [comment]
Done!

**Pull request merged**
